# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 23:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 7, 23, 5, 51, 208000, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='independent',
            name='imageFile',
            field=models.ImageField(null=True, upload_to=b'BuscoAyuda/static/images'),
        ),
        migrations.AlterField(
            model_name='independent',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Job'),
        ),
    ]
