# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160206_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='independent',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Independent'),
        ),
    ]
