# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160206_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='independent',
        ),
    ]
