# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160206_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='independent',
            name='created',
            field=models.DateTimeField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='independent',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='./polls/templates/polls/images'),
        ),
    ]
